sudo: required
services:
  - docker

before_install:
  - docker build -t palankarravi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true palankarravi/docker-react npm run test -- --coverage